CREATE TABLE source
(
    id   bigint primary key generated by default as identity,
    name varchar(255) not null
);

create table topic
(
    id   bigint primary key generated by default as identity,
    name varchar(255) not null
);

create table news
(
    id        bigint primary key generated by default as identity,
    news      varchar not null,
    topic_id     bigint  not null references topic (id),
    source_id bigint  not null references source (id)
);