CREATE TABLE source
(
    id     bigint primary key generated by default as identity,
    source varchar(255) not null
);

create table source_news
(
    id        bigint primary key generated by default as identity,
    topic     varchar(255),
    news      varchar,
    source_id bigint references source (id)
);